package com.example.atlasevents.data.model;
import com.example.atlasevents.data.NotificationRepository;
import com.example.atlasevents.utils.NotificationHelper;

import java.util.Date;
/***
 * @Muaaz Saif
 * @version 1
 *
 * This class works off a client-side model, instead of a cloud based model to create notifications
 *
 * the model for this in-app notification document shpuld be  stored in:
 *  *   users/{recipientUid}/notifications/{notifId}
 *
 *   Represents a notification entity in the application.
 *  Notifications are used to communicate events, updates, and alerts to users
 *  regarding events they are involved in or system-wide announcements.
 *
 *  <p>This class maps to Firestore documents in the users/{email}/notifications collection
 *  and supports both user-facing notifications and administrative notification logs.</p>
 *
 * @See NotificationListner
 * @see  NotificationRepository
 * @see NotificationHelper
 *
 * @ since: 2nd November 2025
 */
public class Notification {
    private String groupType;
    private String eventName;
    private String notificationId;
    private String title;
    private String message;
    private String eventId;
    private String fromOrganizeremail;
    private boolean read;
    private Date createdAt;

    /**
     * Default constructor required for Firestore data mapping.
     * Firestore uses this constructor when deserializing documents from the database.
     */
    public Notification(){}

    /**
     * Constructs a new Notification with all required fields.
     *
     * @param title The title/heading of the notification
     * @param message The detailed message content of the notification
     * @param eventId The unique identifier of the related event
     * @param fromOrganizeremail The email of the organizer who sent the notification
     * @param eventName The display name of the related event
     * @param groupType The category or group this notification belongs to (e.g., "Waiting List", "Chosen Entrants")
     */
    public Notification(String title, String message, String eventId, String fromOrganizeremail, String eventName, String groupType) {
        this.title = title;
        this.message = message;
        this.eventId = eventId;
        this.fromOrganizeremail = fromOrganizeremail;
        this.eventName = eventName;
        this.read = false;
        this.groupType = groupType;
    }
    /**
     * Gets the unique identifier for this notification.
     *
     * @return The notification ID, typically auto-generated by Firestore
     */
    public String getNotificationId() { return notificationId; }
    /**
     * Sets the unique identifier for this notification.
     *
     * @param notificationId The notification ID to set
     */
    public void setNotificationId(String notificationId) { this.notificationId = notificationId; }
    /**
     * Gets the title of the notification.
     *
     * @return The notification title
     */
    public String getTitle() { return title; }

    /**
     * Sets the title of the notification.
     *
     * @param title The title to set
     */
    public void setTitle(String title) { this.title = title; }

    /**
     * Gets the message content of the notification.
     *
     * @return The notification message
     */

    public String getMessage() { return message; }
    /**
     * Sets the message content of the notification.
     *
     * @param message The message to set
     */
    public void setMessage(String message) { this.message = message; }
    /**
     * gets the event ID associated with this notification.
     *
     * @return The relevant event ID
     */
    public String getEventId() { return eventId; }
    /**
     * Sets the event ID associated with this notification.
     *
     * @param eventId The event ID to set
     */
    public void setEventId(String eventId) { this.eventId = eventId; }
    /**
     * Gets the email of the organizer who sent this notification.
     *
     * @return The organizer's email
     */
    public String getFromOrganizeremail() { return fromOrganizeremail; }
    /**
     * Sets the email of the organizer who sent this notification.
     *
     * @paramfromOrganizeremail The organizer's email to set
     */
    public void setFromOrganizeremail(String fromOrganizeremail) { this.fromOrganizeremail = fromOrganizeremail; }

    /**
     * Checks if the notification has been read by the recipient.
     *
     * @return true if the notification has been read, false otherwise
     */
    public boolean isRead() { return read; }

    /**
     * Sets the read status of the notification.
     *
     * @param read The read status to set
     */
    public void setRead(boolean read) { this.read = read; }
    /**
     * Gets the creation timestamp of the notification.
     *
     * @return The date when the notification was created
     */
    public Date getCreatedAt() { return createdAt; }
    /**
     * Sets the creation timestamp of the notification.
     *
     * @param createdAt The creation date to set
     */
    public void setCreatedAt(Date createdAt) { this.createdAt = createdAt; }
/**
 * Gets the name of the event associated with this notification.
 *
 * @return The event name
 */

    public String getEventName() { return eventName; }
    /**
     * Sets the name of the event associated with this notification.
     *
     * @param eventName The event name to set
     */
    public void setEventName(String eventName) { this.eventName = eventName; }

/**
 * Gets the group type/category of this notification.
 *
 * @return The group type (e.g., "Waiting List", "Chosen Entrants", "Cancelled Entrants")
 */

    public String getGroupType() { return groupType; }

    /**
     * Sets the group type/category of this notification.
     *
     * @param groupType The group type to set
     */
    public void setGroupType(String groupType) { this.groupType = groupType; }
}

